### PR TITLE
Pull req for fixing in Python 3.7

### PR DESCRIPTION
**Pull request by yonyonson**
Packge doesn't runs om Python 3.7 as of now, that would be nice with pip version working

### CODE REVIEW

**Comment by jeffwheeler** [comment]
Is there any reason this pull request hasn't been accepted? I am also running into this issue.

**Comment by muyajil** [comment]
I would also be glad if this PR would be merged.

**Comment by crystal-li** [comment]
@gchiam would love this to be merged so that the client is usable in python 3.7

**Review by gchiam — APPROVED** [review]
Thanks for doing this.

**Pull request merged**
